# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

pod 'pop', '~> 1.0'

target 'TFNetEaseMenu' do

end

target 'TFNetEaseMenuTests' do

end

target 'TFNetEaseMenuUITests' do

end

